from __future__ import annotations

import argparse
import os
import random
import secrets
import sqlite3
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Tuple

from werkzeug.security import generate_password_hash

# ----------------------------
# Config
# ----------------------------
DEFAULT_PASSWORD = "admin"

ROLES = {
    "manager": "manager",
    "recruiter": "recruiter",
    "interviewer": "interviewer",
    "admin": "admin",
}

JOB_STATUSES = ["draft", "pending_review", "changes_requested", "published", "closed"]
APP_STATUSES = ["new", "in_review", "shortlisted", "interview", "rejected", "offered", "hired", "withdrawn"]

# Interview statuses used by this seed (keep it consistent with your app)
INTERVIEW_STATUSES = ["planned", "completed"]


def now_sql() -> str:
    return datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")


def days_from_now(days: int, hour: int = 10, minute: int = 0) -> str:
    dt = datetime.utcnow() + timedelta(days=days)
    dt = dt.replace(hour=hour, minute=minute, second=0, microsecond=0)
    return dt.strftime("%Y-%m-%d %H:%M:%S")


def connect(db_path: Path) -> sqlite3.Connection:
    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON;")
    return conn


def create_dummy_pdf(path: Path, title: str) -> None:
    """
    Minimal-ish PDF content (enough to download/open in many viewers).
    """
    content = f"""%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>
endobj
4 0 obj
<< /Length 180 >>
stream
BT
/F1 20 Tf
72 770 Td
({title}) Tj
/F1 12 Tf
72 740 Td
(Demo CV - dummy file) Tj
72 720 Td
(Generated by seed script) Tj
ET
endstream
endobj
5 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj
xref
0 6
0000000000 65535 f
0000000010 00000 n
0000000060 00000 n
0000000117 00000 n
0000000282 00000 n
0000000507 00000 n
trailer
<< /Size 6 /Root 1 0 R >>
startxref
600
%%EOF
"""
    path.write_bytes(content.encode("utf-8"))


def reset_tables(conn: sqlite3.Connection) -> None:
    """
    Delete in a safe order because of FK constraints.
    """
    tables_in_order = [
        "evaluation_scores",
        "evaluations",
        "interview_interviewers",
        "interviews",
        "phase_interviewers",
        "interview_phases",
        "applications",
        "template_aspects",
        "template_versions",
        "template_groups",
        "notifications",
        "audit_log",
        "vacancies",
        "candidates",
        "users",
    ]
    for t in tables_in_order:
        conn.execute(f"DELETE FROM {t};")
    conn.commit()


def insert_user(conn: sqlite3.Connection, email: str, role: str, full_name: str) -> int:
    pw_hash = generate_password_hash(DEFAULT_PASSWORD)
    cur = conn.execute(
        """
        INSERT INTO users (email_address, password_hash, full_name, user_role, is_active)
        VALUES (?, ?, ?, ?, 1)
        """,
        (email.lower(), pw_hash, full_name, role),
    )
    return int(cur.lastrowid)


def insert_candidate(conn: sqlite3.Connection, email: str, name: str, with_password: bool = True) -> int:
    pw_hash = generate_password_hash(DEFAULT_PASSWORD) if with_password else None
    cur = conn.execute(
        """
        INSERT INTO candidates (email_address, password_hash, full_name, phone_number, is_active, created_at, updated_at)
        VALUES (?, ?, ?, ?, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
        """,
        (
            email.lower(),
            pw_hash,
            name,
            f"+32 4{random.randint(70, 99)} {random.randint(100, 999)} {random.randint(100, 999)}",
        ),
    )
    return int(cur.lastrowid)


def insert_template_bundle(
    conn: sqlite3.Connection,
    created_by_user_id: int,
    group_name: str,
    version_label: str,
    aspects: List[Tuple[str, str]],
) -> Tuple[int, int, List[int]]:
    """
    Returns: (group_id, version_id, aspect_ids)
    Creates a group + a published version + aspects
    """
    cur = conn.execute(
        """
        INSERT INTO template_groups (template_name, template_description, created_by_user_id)
        VALUES (?, ?, ?)
        """,
        (group_name, f"Demo template: {group_name}", created_by_user_id),
    )
    group_id = int(cur.lastrowid)

    cur = conn.execute(
        """
        INSERT INTO template_versions (
            template_group_id, version_number, version_label,
            status, created_by_user_id, published_at
        )
        VALUES (?, 1, ?, 'published', ?, CURRENT_TIMESTAMP)
        """,
        (group_id, version_label, created_by_user_id),
    )
    version_id = int(cur.lastrowid)

    aspect_ids: List[int] = []
    for idx, (title, desc) in enumerate(aspects, start=1):
        cur = conn.execute(
            """
            INSERT INTO template_aspects (
                template_version_id, aspect_title, aspect_description, weight,
                min_score, max_score, is_required, sort_order
            )
            VALUES (?, ?, ?, 1.0, 1, 5, 1, ?)
            """,
            (version_id, title, desc, idx * 10),
        )
        aspect_ids.append(int(cur.lastrowid))

    return group_id, version_id, aspect_ids


def insert_vacancy(
    conn: sqlite3.Connection,
    manager_id: int,
    title: str,
    department: str,
    description: str,
    status: str,
    reviewed_by_user_id: int | None = None,
) -> int:
    cur = conn.execute(
        """
        INSERT INTO vacancies (
            title, department, description,
            location, employment_type, experience_level,
            manager_id, status,
            submitted_at, reviewed_by_user_id, reviewed_at, published_at,
            created_at, updated_at
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
        """,
        (
            title,
            department,
            description,
            "Brussels",
            "full-time",
            "junior",
            manager_id,
            status,
            now_sql() if status in ("pending_review", "published", "changes_requested") else None,
            reviewed_by_user_id if status in ("published", "changes_requested") else None,
            now_sql() if status in ("published", "changes_requested") else None,
            now_sql() if status == "published" else None,
        ),
    )
    return int(cur.lastrowid)


def insert_phase(
    conn: sqlite3.Connection,
    vacancy_id: int,
    name: str,
    seq: int,
    template_version_id: int,
    is_active: int = 1,
) -> int:
    cur = conn.execute(
        """
        INSERT INTO interview_phases (vacancy_id, phase_name, sequence_number, template_version_id, is_active)
        VALUES (?, ?, ?, ?, ?)
        """,
        (vacancy_id, name, seq, template_version_id, is_active),
    )
    return int(cur.lastrowid)


def assign_phase_interviewers(conn: sqlite3.Connection, phase_id: int, interviewer_ids: List[int]) -> None:
    for iid in interviewer_ids:
        conn.execute(
            """
            INSERT OR IGNORE INTO phase_interviewers (phase_id, interviewer_user_id)
            VALUES (?, ?)
            """,
            (phase_id, iid),
        )


def insert_application(
    conn: sqlite3.Connection,
    vacancy_id: int,
    candidate_id: int,
    status: str,
    resume_storage_filename: str | None,
    cover_letter: str,
) -> int:
    token = secrets.token_urlsafe(24)
    cur = conn.execute(
        """
        INSERT INTO applications (
            vacancy_id, candidate_id, status,
            applied_at,
            gdpr_consent, gdpr_consent_at,
            status_updated_at, status_updated_by_candidate_id,
            cover_letter,
            resume_original_filename, resume_storage_filename,
            status_view_token
        )
        VALUES (?, ?, ?, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ?, ?, ?, ?, ?)
        """,
        (
            vacancy_id,
            candidate_id,
            status,
            candidate_id,
            cover_letter,
            "cv.pdf" if resume_storage_filename else None,
            resume_storage_filename,
            token,
        ),
    )
    return int(cur.lastrowid)


def insert_interview(
    conn: sqlite3.Connection,
    application_id: int,
    phase_id: int,
    scheduled_start: str,
    status: str,
    created_by_user_id: int,
    meeting_link: str | None = None,
    notes: str | None = None,
) -> int:
    cur = conn.execute(
        """
        INSERT INTO interviews (
            application_id, phase_id,
            scheduled_start, scheduled_end,
            location, meeting_link,
            status, created_by_user_id, created_at,
            completed_at, notes
        )
        VALUES (?, ?, ?, NULL, NULL, ?, ?, ?, CURRENT_TIMESTAMP,
                CASE WHEN ? = 'completed' THEN CURRENT_TIMESTAMP ELSE NULL END,
                ?)
        """,
        (
            application_id,
            phase_id,
            scheduled_start,
            meeting_link,
            status,
            created_by_user_id,
            status,
            notes or "Demo interview notes",
        ),
    )
    return int(cur.lastrowid)


def insert_interview_interviewers(conn: sqlite3.Connection, interview_id: int, interviewer_ids: List[int]) -> None:
    # first = primary, rest = panel
    for idx, iid in enumerate(interviewer_ids):
        role = "primary" if idx == 0 else "panel"
        conn.execute(
            """
            INSERT OR IGNORE INTO interview_interviewers (interview_id, interviewer_user_id, interviewer_role)
            VALUES (?, ?, ?)
            """,
            (interview_id, iid, role),
        )


def insert_evaluation_with_scores(
    conn: sqlite3.Connection,
    interview_id: int,
    interviewer_user_id: int,
    template_version_id: int,
    aspect_ids: List[int],
    status: str,
    overall_comment: str | None = None,
) -> int:
    cur = conn.execute(
        """
        INSERT INTO evaluations (
            interview_id, interviewer_user_id, template_version_id,
            evaluation_status, overall_comment, created_at, updated_at, submitted_at
        )
        VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
                CASE WHEN ? = 'submitted' THEN CURRENT_TIMESTAMP ELSE NULL END)
        """,
        (
            interview_id,
            interviewer_user_id,
            template_version_id,
            status,
            overall_comment
            or ("Sterke kandidaat, goede communicatie." if status == "submitted" else "Nog bezig met evaluatie..."),
            status,
        ),
    )
    evaluation_id = int(cur.lastrowid)

    for aid in aspect_ids:
        score = random.randint(3, 5) if status == "submitted" else random.randint(1, 4)
        conn.execute(
            """
            INSERT INTO evaluation_scores (evaluation_id, template_aspect_id, score, comment)
            VALUES (?, ?, ?, ?)
            """,
            (
                evaluation_id,
                aid,
                score,
                "Sterk" if score >= 4 else ("OK" if score >= 3 else "Kan beter"),
            ),
        )

    return evaluation_id


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--reset", action="store_true", help="Delete existing data first")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for reproducible demo data")
    args = parser.parse_args()

    random.seed(args.seed)

    base_dir = Path(__file__).resolve().parent  # werving_app/
    db_path = Path(os.environ.get("SQLITE_DB_PATH", str(base_dir / "database.db")))

    uploads_dir = base_dir / "uploads"
    uploads_dir.mkdir(exist_ok=True)

    conn = connect(db_path)

    if args.reset:
        reset_tables(conn)

    # ----------------------------
    # Users (internal)
    # ----------------------------
    manager_id = insert_user(conn, "manager@bedrijf.be", ROLES["manager"], "Hoi, Manager")
    recruiter_id = insert_user(conn, "recruiter@bedrijf.be", ROLES["recruiter"], "Hoi, Recruiter")
    admin_id = insert_user(conn, "admin@bedrijf.be", ROLES["admin"], "Admin User")

    # ✅ Basis interviewer (zoals gevraagd)
    base_interviewer_id = insert_user(conn, "interviewer@bedrijf.be", ROLES["interviewer"], "Basis Interviewer")

    # ✅ Extra interviewers (voor demo panel)
    extra_interviewer_ids: List[int] = []
    for i in range(1, 8):  # 7 extra interviewers
        extra_interviewer_ids.append(
            insert_user(conn, f"interviewer{i}@bedrijf.be", ROLES["interviewer"], f"Interviewer {i}")
        )

    # handige lijst voor random picks
    interviewer_ids: List[int] = [base_interviewer_id] + extra_interviewer_ids

    # ----------------------------
    # Templates (meerdere bundles, published)
    # ----------------------------
    screening_aspects = [
        ("Motivatie", "Is de motivatie duidelijk en relevant?"),
        ("Communicatie", "Kan de kandidaat helder communiceren?"),
        ("Beschikbaarheid", "Past de beschikbaarheid bij de planning?"),
        ("Basis fit", "Matcht de kandidaat met de vacature op hoofdlijnen?"),
        ("Taal", "Nederlands/Frans/Engels voldoende voor de rol?"),
    ]
    tech_aspects = [
        ("Technische kennis", "Begrip van basisconcepten en praktijk."),
        ("Probleemoplossend", "Aanpak en redenering bij challenges."),
        ("Code kwaliteit", "Leesbaarheid, structuur, best practices."),
        ("Tooling", "Kennis van relevante tools/stack."),
        ("Debugging", "Kan issues methodisch opsporen?"),
    ]
    culture_aspects = [
        ("Team fit", "Samenwerking en attitude."),
        ("Leren", "Leergierigheid en groeipotentieel."),
        ("Verantwoordelijkheid", "Ownership en betrouwbaarheid."),
        ("Stressbestendig", "Omgaan met deadlines en druk."),
        ("Feedback", "Open voor feedback en verbeteren."),
    ]
    leadership_aspects = [
        ("Ownership", "Neemt initiatief en verantwoordelijkheid."),
        ("Stakeholders", "Communiceert duidelijk met verschillende profielen."),
        ("Planning", "Kan prioriteiten stellen en plannen."),
        ("Mentoring", "Kan kennis delen en begeleiden."),
    ]

    _, tv_screening, aspects_screening = insert_template_bundle(
        conn, recruiter_id, "Recruiter Screening", "v1 - Screening", screening_aspects
    )
    _, tv_tech, aspects_tech = insert_template_bundle(
        conn, recruiter_id, "Technical Interview", "v1 - Tech", tech_aspects
    )
    _, tv_culture, aspects_culture = insert_template_bundle(
        conn, recruiter_id, "Culture Fit", "v1 - Culture", culture_aspects
    )
    _, tv_lead, aspects_lead = insert_template_bundle(
        conn, recruiter_id, "Leadership / Senior", "v1 - Lead", leadership_aspects
    )

    # ----------------------------
    # Vacancies (mix van statussen voor demo)
    # ----------------------------
    vac_support_id = insert_vacancy(
        conn,
        manager_id=manager_id,
        title="Junior IT Support",
        department="IT",
        description="Support tickets, basic networking, Windows/Linux, user support.",
        status="published",
        reviewed_by_user_id=recruiter_id,
    )
    vac_python_id = insert_vacancy(
        conn,
        manager_id=manager_id,
        title="Medior Python Developer",
        department="IT",
        description="APIs bouwen in Python, testing, CI/CD, SQL, code reviews.",
        status="pending_review",
        reviewed_by_user_id=None,
    )
    vac_sales_id = insert_vacancy(
        conn,
        manager_id=manager_id,
        title="Inside Sales Representative",
        department="Sales",
        description="Lead opvolging, prospectie, CRM, targets behalen.",
        status="changes_requested",
        reviewed_by_user_id=recruiter_id,
    )
    vac_hr_id = insert_vacancy(
        conn,
        manager_id=manager_id,
        title="HR Assistant",
        department="HR",
        description="Administratie, onboarding, planning, ondersteuning HR team.",
        status="draft",
        reviewed_by_user_id=None,
    )
    vac_closed_id = insert_vacancy(
        conn,
        manager_id=manager_id,
        title="Frontend Developer (Closed)",
        department="IT",
        description="Vacature is afgesloten (demo status closed).",
        status="closed",
        reviewed_by_user_id=recruiter_id,
    )

    # ----------------------------
    # Interview phases (per vacature)
    # ----------------------------
    # Published Support vacancy: 3 fases (screening, tech, culture)
    sup_ph1 = insert_phase(conn, vac_support_id, "Recruiter screening", 1, tv_screening, is_active=1)
    sup_ph2 = insert_phase(conn, vac_support_id, "Technical interview", 2, tv_tech, is_active=1)
    sup_ph3 = insert_phase(conn, vac_support_id, "Culture fit", 3, tv_culture, is_active=1)

    # Pending Python vacancy: 2 fases (screening, tech) - later uitbreidbaar
    py_ph1 = insert_phase(conn, vac_python_id, "Recruiter screening", 1, tv_screening, is_active=1)
    py_ph2 = insert_phase(conn, vac_python_id, "Technical interview", 2, tv_tech, is_active=1)

    # Changes requested Sales vacancy: 2 fases (screening, culture)
    sales_ph1 = insert_phase(conn, vac_sales_id, "Recruiter screening", 1, tv_screening, is_active=1)
    sales_ph2 = insert_phase(conn, vac_sales_id, "Culture fit", 2, tv_culture, is_active=1)

    # Draft HR vacancy: (fases wel aanwezig, maar eventueel inactive voor demo)
    hr_ph1 = insert_phase(conn, vac_hr_id, "Recruiter screening", 1, tv_screening, is_active=0)
    hr_ph2 = insert_phase(conn, vac_hr_id, "Culture fit", 2, tv_culture, is_active=0)

    # Closed vacancy: fases inactive
    closed_ph1 = insert_phase(conn, vac_closed_id, "Recruiter screening", 1, tv_screening, is_active=0)
    closed_ph2 = insert_phase(conn, vac_closed_id, "Technical interview", 2, tv_tech, is_active=0)

    # ----------------------------
    # Phase interviewers (zodat je UI altijd interviewers kan tonen)
    # ----------------------------
    # Support vacancy: fase 2 & 3 krijgen panel interviewers incl. basis interviewer
    assign_phase_interviewers(conn, sup_ph2, [base_interviewer_id] + extra_interviewer_ids[:4])   # basis + 1..4
    assign_phase_interviewers(conn, sup_ph3, extra_interviewer_ids[2:6] + [base_interviewer_id])  # 3..6 + basis

    # Python vacancy: fase 2 krijgt basis + enkele extras
    assign_phase_interviewers(conn, py_ph2, [base_interviewer_id] + extra_interviewer_ids[4:7])

    # Sales vacancy: culture panel
    assign_phase_interviewers(conn, sales_ph2, [base_interviewer_id] + extra_interviewer_ids[1:3])

    conn.commit()

    # ----------------------------
    # Candidates + Applications (veel variatie)
    # ----------------------------
    candidate_names = [
        "Alex Peeters", "Sophie Janssens", "Mehmet Demir", "Laura Vermeulen",
        "Noah Dubois", "Emma De Smet", "Milan Van den Broeck", "Lina Ait Benali",
        "Younes El Amrani", "Julie Maes", "Thomas Lambert", "Ines Van Acker",
        "Samira Ben Youssef", "Ruben Willems",
    ]

    candidate_ids: List[int] = []
    applications: List[Dict] = []

    def make_cv(idx: int, name: str) -> str:
        cv_filename = f"cv_candidate{idx}.pdf"
        create_dummy_pdf(uploads_dir / cv_filename, f"CV - {name}")
        return cv_filename

    vacancy_pool = [
        (vac_support_id, "support"),
        (vac_python_id, "python"),
        (vac_sales_id, "sales"),
        (vac_hr_id, "hr"),
        (vac_closed_id, "closed"),
    ]

    for idx, name in enumerate(candidate_names, start=1):
        email = f"candidate{idx}@mail.com"
        with_pw = (idx % 2 == 0)
        cid = insert_candidate(conn, email, name, with_password=with_pw)
        candidate_ids.append(cid)

        # Niet iedereen heeft een CV (demo edge case)
        has_cv = (idx % 5 != 0)
        cv_filename = make_cv(idx, name) if has_cv else None

        vac_id, tag = random.choice(vacancy_pool)

        # Meer realistische status per vacature
        if vac_id == vac_support_id:
            status = random.choice(["new", "in_review", "shortlisted", "interview"])
        elif vac_id == vac_python_id:
            status = random.choice(["new", "in_review", "shortlisted"])
        elif vac_id == vac_sales_id:
            status = random.choice(["in_review", "shortlisted", "rejected"])
        elif vac_id == vac_hr_id:
            status = random.choice(["new", "withdrawn"])
        else:
            status = random.choice(["rejected", "withdrawn"])

        app_id = insert_application(
            conn,
            vacancy_id=vac_id,
            candidate_id=cid,
            status=status,
            resume_storage_filename=cv_filename,
            cover_letter=f"Beste, ik ben {name} en ik ben gemotiveerd om te solliciteren ({tag}).",
        )
        applications.append({"application_id": app_id, "candidate_id": cid, "status": status, "vacancy_id": vac_id})

    # Extra toepassingen voor variatie (zelfde kandidaat kan meerdere keren solliciteren in demo)
    for extra_idx in range(1, 7):
        cid = random.choice(candidate_ids)
        cv_filename = f"cv_extra{extra_idx}.pdf"
        create_dummy_pdf(uploads_dir / cv_filename, f"Extra CV {extra_idx}")

        vac_id = random.choice([vac_support_id, vac_support_id, vac_python_id, vac_sales_id])
        status = random.choice(["rejected", "withdrawn", "offered", "hired", "in_review"])

        app_id = insert_application(
            conn,
            vacancy_id=vac_id,
            candidate_id=cid,
            status=status,
            resume_storage_filename=cv_filename,
            cover_letter="Extra sollicitatie (demo).",
        )
        applications.append({"application_id": app_id, "candidate_id": cid, "status": status, "vacancy_id": vac_id})

    # ----------------------------
    # Forceer voldoende "interview" status op published Support vacancy
    # ----------------------------
    support_apps = [a for a in applications if a["vacancy_id"] == vac_support_id]
    interview_support_apps = [a for a in support_apps if a["status"] == "interview"]

    if len(interview_support_apps) < 6:
        need = 6 - len(interview_support_apps)
        # pak eerst de meest geschikte (shortlisted/in_review/new)
        candidates_to_promote = [a for a in support_apps if a["status"] in ("shortlisted", "in_review", "new")]
        random.shuffle(candidates_to_promote)
        for a in candidates_to_promote[:need]:
            conn.execute(
                "UPDATE applications SET status = 'interview', status_updated_at = CURRENT_TIMESTAMP WHERE id = ?",
                (a["application_id"],),
            )
            a["status"] = "interview"

        interview_support_apps = [a for a in support_apps if a["status"] == "interview"]

    conn.commit()

    # ----------------------------
    # Interviews + Evaluations (sterke demo scenario's)
    # ----------------------------
    # Scenario A: fase 2 completed met 2 interviewers: 1 submitted, 1 draft
    # Scenario B: fase 3 completed met 2 interviewers: beiden submitted (decision page demo)
    # Scenario C: enkele planned interviews met meeting links (Teams)
    random.shuffle(interview_support_apps)

    # Maak voor de eerste 8 interview-apps interviews door de fases heen
    for idx, a in enumerate(interview_support_apps[:8], start=1):
        app_id = a["application_id"]

        # Phase 1: recruiter screening (recruiter is interviewer)
        ph1_status = "completed" if idx % 3 == 0 else "planned"
        i1 = insert_interview(
            conn,
            application_id=app_id,
            phase_id=sup_ph1,
            scheduled_start=days_from_now(idx, hour=9 + (idx % 3)),
            status=ph1_status,
            created_by_user_id=recruiter_id,
            meeting_link="https://teams.microsoft.com/l/meetup-join/demo-phase1" if idx % 2 == 0 else None,
            notes="Recruiter screening: basis vragen + motivatie.",
        )
        insert_interview_interviewers(conn, i1, [recruiter_id])

        # Phase 2: tech interview (minstens 1x forceer basis interviewer)
        if idx == 1:
            chosen2 = [base_interviewer_id, random.choice(extra_interviewer_ids)]
        else:
            chosen2 = random.sample(interviewer_ids, k=2)

        i2_status = "completed" if idx in (1, 2, 4, 6) else "planned"
        i2 = insert_interview(
            conn,
            application_id=app_id,
            phase_id=sup_ph2,
            scheduled_start=days_from_now(idx + 1, hour=11),
            status=i2_status,
            created_by_user_id=recruiter_id,
            meeting_link="https://teams.microsoft.com/l/meetup-join/demo-phase2",
            notes="Tech interview: praktische vragen + mini case.",
        )
        insert_interview_interviewers(conn, i2, chosen2)

        if i2_status == "completed":
            # demo: 1 submitted, 1 draft
            insert_evaluation_with_scores(
                conn,
                i2,
                chosen2[0],
                tv_tech,
                aspects_tech,
                status="submitted",
                overall_comment="Sterk in basics, goede aanpak bij case.",
            )
            insert_evaluation_with_scores(
                conn,
                i2,
                chosen2[1],
                tv_tech,
                aspects_tech,
                status="draft",
                overall_comment="Nog bezig, moet score/feedback verfijnen.",
            )

        # Phase 3: voor een paar kandidaten ook culture fit
        if idx in (2, 3, 5):
            chosen3 = random.sample(interviewer_ids, k=2)
            i3_status = "completed" if idx in (2, 5) else "planned"
            i3 = insert_interview(
                conn,
                application_id=app_id,
                phase_id=sup_ph3,
                scheduled_start=days_from_now(idx + 3, hour=14),
                status=i3_status,
                created_by_user_id=recruiter_id,
                meeting_link="https://teams.microsoft.com/l/meetup-join/demo-phase3" if idx % 2 == 1 else None,
                notes="Culture fit: team samenwerking + feedback scenario.",
            )
            insert_interview_interviewers(conn, i3, chosen3)

            if i3_status == "completed":
                # mix: meestal beide submitted
                insert_evaluation_with_scores(conn, i3, chosen3[0], tv_culture, aspects_culture, status="submitted")
                insert_evaluation_with_scores(conn, i3, chosen3[1], tv_culture, aspects_culture, status="submitted")

    # ✅ “Decision page” killer demo: fase 3 completed met basis interviewer + 1 extra, beiden submitted
    decision_app_id = interview_support_apps[0]["application_id"]
    chosen_decision = [base_interviewer_id, random.choice(extra_interviewer_ids[2:6])]

    decision_i3 = insert_interview(
        conn,
        application_id=decision_app_id,
        phase_id=sup_ph3,
        scheduled_start=days_from_now(5, hour=15),
        status="completed",
        created_by_user_id=recruiter_id,
        meeting_link="https://teams.microsoft.com/l/meetup-join/demo-decision",
        notes="Decision demo: alle evaluaties ingediend.",
    )
    insert_interview_interviewers(conn, decision_i3, chosen_decision)
    insert_evaluation_with_scores(conn, decision_i3, chosen_decision[0], tv_culture, aspects_culture, status="submitted")
    insert_evaluation_with_scores(conn, decision_i3, chosen_decision[1], tv_culture, aspects_culture, status="submitted")

    # Extra: een paar interviews op de Python vacancy (pending_review) om te tonen dat workflow al klaar staat
    py_apps = [a for a in applications if a["vacancy_id"] == vac_python_id]
    random.shuffle(py_apps)
    for j, a in enumerate(py_apps[:3], start=1):
        app_id = a["application_id"]
        # zet status op interview voor demo
        conn.execute("UPDATE applications SET status='interview', status_updated_at=CURRENT_TIMESTAMP WHERE id=?", (app_id,))
        i_py = insert_interview(
            conn,
            application_id=app_id,
            phase_id=py_ph1,
            scheduled_start=days_from_now(2 + j, hour=10),
            status="planned",
            created_by_user_id=recruiter_id,
            meeting_link=None,
            notes="Python vacancy screening (pending_review).",
        )
        insert_interview_interviewers(conn, i_py, [recruiter_id])

    # ----------------------------
    # Notifications (in-app demo)
    # ----------------------------
    conn.execute(
        """
        INSERT INTO notifications (recipient_type, recipient_id, channel, subject, body, delivery_status)
        VALUES ('user', ?, 'in_app', 'Welkom recruiter', 'Je demo database is gevuld met nepdata.', 'sent')
        """,
        (recruiter_id,),
    )
    conn.execute(
        """
        INSERT INTO notifications (recipient_type, recipient_id, channel, subject, body, delivery_status)
        VALUES ('user', ?, 'in_app', 'Nieuwe interviews gepland', 'Er staan meerdere interviews gepland voor deze week.', 'sent')
        """,
        (recruiter_id,),
    )
    conn.execute(
        """
        INSERT INTO notifications (recipient_type, recipient_id, channel, subject, body, delivery_status)
        VALUES ('user', ?, 'in_app', 'Evaluaties in progress', 'Minstens één interview heeft 1 submitted + 1 draft evaluatie.', 'sent')
        """,
        (recruiter_id,),
    )

    conn.commit()
    conn.close()

    print("\n✅ Demo data seeded!")
    print(f"Random seed: {args.seed}")
    print("Login accounts (allemaal zelfde wachtwoord):", DEFAULT_PASSWORD)
    print(" - Manager: manager@bedrijf.be")
    print(" - Recruiter: recruiter@bedrijf.be")
    print(" - Admin: admin@bedrijf.be")
    print(" - Interviewer (basis): interviewer@bedrijf.be")
    print(" - Interviewers (extra): interviewer1@bedrijf.be ... interviewer7@bedrijf.be")
    print("\nDemo tips:")
    print(" - Recruiter → Sollicitaties → plan interviews → Interviews pagina")
    print(" - Er is een 'decision demo' interview (fase 3) met 2x submitted evaluaties.")
    print(" - Er is een fase 2 interview met 1 submitted + 1 draft evaluatie (progress demo).")
    print(" - Sommige kandidaten hebben geen CV (edge case demo).")
    print(" - Er zijn vacatures in draft/pending_review/changes_requested/published/closed.\n")


if __name__ == "__main__":
    main()
